;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;                                                                 ;;
;; Copyright (C) KolibriOS team 2018. All rights reserved.         ;;
;; Distributed under terms of the GNU General Public License       ;;
;;                                                                 ;;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

dump_cpuid db 'CPUID ', 0

winmain_title db 'kcpuid', 0
vendor_title db 'Vendor:', 0
brand_title db 'Brand:', 0
codename_title db 'Codename:', 0
unknown_codename db 'Unknown', 0
